<script setup>
import { ref } from 'vue'
import { api } from './api.js'
// 匹配页面只提交临时目标和候选，不在前端保存匹配结果。
const mode = ref('normal'), limit = ref(10), loading = ref(false), error = ref(''), result = ref(null)
const target = ref({ itemId: '', title: '', fileName: '', mediaType: 'episode', seasonNumber: null, episodeNumber: null, year: null }), candidatesText = ref('[]'), numberingText = ref('')
async function resolve() { error.value = ''; result.value = null; let candidates, numbering = null; try { candidates = JSON.parse(candidatesText.value); if (!Array.isArray(candidates)) throw new Error('候选必须是 JSON 数组'); if (numberingText.value.trim()) numbering = JSON.parse(numberingText.value) } catch (e) { error.value = `JSON 格式无效：${e.message}`; return } if (!target.value.title && !target.value.fileName) { error.value = '至少填写标题或文件名'; return } loading.value = true; try { result.value = await api.resolveMatch({ mode: 'normal', target: target.value, candidates, resultLimit: limit.value, numberingContext: numbering }) } catch (e) { error.value = e.message } finally { loading.value = false } }
</script>
<template><section class="panel"><el-card shadow="never"><template #header>无状态媒体匹配</template><el-alert title="仅根据本次提交的目标和候选进行判断，不下载、不保存绑定、不自动应用结果。" type="info" :closable="false" /><el-alert v-if="error" :title="error" type="error" :closable="false" /><el-form label-position="top"><el-form-item label="匹配策略"><span>由 DLL 后端配置决定优先方式及是否回退，本页不能覆盖。</span></el-form-item><div class="grid"><el-form-item label="Item ID"><el-input v-model="target.itemId" /></el-form-item><el-form-item label="媒体类型"><el-input v-model="target.mediaType" /></el-form-item><el-form-item label="标题"><el-input v-model="target.title" /></el-form-item><el-form-item label="文件名"><el-input v-model="target.fileName" /></el-form-item><el-form-item label="季"><el-input-number v-model="target.seasonNumber" :min="0" /></el-form-item><el-form-item label="集"><el-input-number v-model="target.episodeNumber" :min="0" /></el-form-item><el-form-item label="年份"><el-input-number v-model="target.year" :min="1900" :max="2200" /></el-form-item><el-form-item label="结果条数"><el-input-number v-model="limit" :min="1" :max="100" /></el-form-item></div><el-form-item label="候选 JSON"><el-input v-model="candidatesText" type="textarea" :rows="9" /></el-form-item><el-form-item label="编号映射 JSON（可选）"><el-input v-model="numberingText" type="textarea" :rows="4" placeholder="例如 {&quot;sourceId&quot;:&quot;tvdb&quot;,...}" /></el-form-item><el-button type="primary" :loading="loading" @click="resolve">开始匹配</el-button></el-form></el-card><el-card v-if="result" shadow="never" class="result"><template #header>匹配结果：{{ result.status || result.Status }}</template><p>模式：{{ result.modeUsed || result.ModeUsed }}；选中：{{ result.selectedCandidateId || result.SelectedCandidateId || '无' }}</p><el-alert v-if="result.warnings?.length || result.Warnings?.length" title="存在警告，请查看候选状态" type="warning" :closable="false" /><el-table :data="result.candidates || result.Candidates" stripe><el-table-column prop="candidateId" label="候选 ID" /><el-table-column prop="score" label="分数" width="100" /><el-table-column prop="eligible" label="可用" width="80" /><el-table-column label="解释/冲突"><template #default="{ row }">{{ (row.reasons || row.Reasons || []).join('；') }} {{ (row.conflicts || row.Conflicts || []).join('；') }}</template></el-table-column></el-table></el-card></section></template>
<style scoped>.grid{display:grid;grid-template-columns:repeat(4,minmax(120px,1fr));gap:10px}.result{margin-top:16px}@media(max-width:900px){.grid{grid-template-columns:repeat(2,1fr)}}</style>
