name: Deploy Cloudflare Worker

on:
  push:
    branches: [ main, master ]
    paths:
      - 'cf_worker.js'
      - 'build.js'
      - 'wrangler.toml'
      - '.github/workflows/cloudflare-worker.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'cf_worker.js'
      - 'build.js'
      - 'wrangler.toml'
      - '.github/workflows/cloudflare-worker.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Worker

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Build Worker
      run: node build.js
      env:
        USER_AGENT_LIMITS_CONFIG: ${{ secrets.USER_AGENT_LIMITS_CONFIG }}
        IP_BLACKLIST_CONFIG: ${{ secrets.IP_BLACKLIST_CONFIG }}
        DATA_CENTER_URL: ${{ secrets.DATA_CENTER_URL }}
        DATA_CENTER_API_KEY: ${{ secrets.DATA_CENTER_API_KEY }}
        WORKER_ID: ${{ secrets.WORKER_ID }}
        ENABLE_ASYMMETRIC_AUTH_ENV: ${{ secrets.ENABLE_ASYMMETRIC_AUTH_ENV }}
        ENABLE_DETAILED_LOGGING: ${{ secrets.ENABLE_DETAILED_LOGGING }}
        PRIVATE_KEY_HEX: ${{ secrets.PRIVATE_KEY_HEX }}

    - name: Deploy to Cloudflare Workers
      if: github.event_name != 'pull_request'
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: deploy

    - name: Test deployment (optional)
      if: github.event_name != 'pull_request'
      run: |
        echo "Worker deployed successfully!"
        echo "Worker URL: https://danmu-api.${{ secrets.CLOUDFLARE_SUBDOMAIN || 'workers' }}.dev"